Touristapp/urls.py
from django.urls import path
from .views import * 

app_name='Touristapp'
urlpatterns=[
  path('',HomeView.as_view(),name="home"),
  path('about/',AboutView.as_view(),name="about"),
  path('tour/',TourPackageView.as_view(),name="tourpackage"),
  path('tour/<int:pk>/detail/',TourPackageDetailView.as_view(),name="tourpackagedetail"),
  path('tourpackage/',TourPackageCreateView.as_view(),name="tourpackagecreate"),
  path('tourpackage/<int:pk>/edit/',TourPackageUpdateView.as_view(),name="tourpackageupdate"),
  path('tour/<int:pk>/delete/',TourPackageDeleteView.as_view(),name="tourpackagedelete"),
  path('contact/',ContactUsView.as_view(),name="contactus"),
  path('login/',LoginView.as_view(),name="login"),
  path('logout/',LogoutView.as_view(),name="logout"),
  path('register/',RegistrationView.as_view(),name="registration"),
  path('bankapi/',BankApiView.as_view(),name="bankapi"),
  path('protected-page/',ProtectedView.as_view(),name="protected"),

] 

Touristproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Touristapp.urls')),
    path('blogsite/',include('blogapp.urls')),

]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from .views import * 


app_name='blogapp'
urlpatterns=[
 path('',BlogHomeView.as_view(),name="bloghome"),
 path('bloglist/',BlogListView.as_view(),name="bloglist"),
 path('blog/<int:pk>/detail/',BlogDetailView.as_view(),name="blogdetail"),
 path('blogcreate/',BlogCreateView.as_view(),name="blogcreate"),
 path('blog/<int:pk>/update/',BlogUpdateView.as_view(),name="blogupdate"),
 path('blog/<int:pk>/delete/',BlogDeleteView.as_view(),name="blogdelete"),

]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	title=models.CharField(max_length=200)
	slug=models.SlugField(unique=True)
	image=models.ImageField(upload_to='blogs')
	content=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	author=models.ForeignKey(User,on_delete=models.CASCADE)
	views=models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title
	"""docstring for """

class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    commenter=models.ForeignKey(User,on_delete=models.CASCADE)
    text=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    root=models.ForeignKey("self",on_delete=models.CASCADE,null=True,blank=True)
    #self le chai Comment lai call gareko ho 

    def __str__(self):
        return " comment for "+ self.article.title + " by " + self.commenter.username	

blogapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class BlogForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','slug','image', 'content','views']

blogapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import *
from .models import *
from .forms import *
# Create your views here.

class BlogHomeView(TemplateView):
	template_name="blogapp/bloghome.html"

class BlogListView(ListView):
    template_name="blogapp/bloglist.html"
    model=Article 
    context_object_name='allblog'

class BlogDetailView(DetailView):
    template_name = 'blogapp/blogdetail.html'
    model = Article
    context_object_name = 'blogde'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articlelist'] = Article.objects.all()

        article =self.object
        article.views += 1
        article.save()

        return context


class BlogCreateView(CreateView):
    template_name = 'blogapp/blogcreate.html'
    form_class = BlogForm
    success_url = "/"

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect("Touristapp:login")
        return super().dispatch(request,*args,**kwargs)

    def form_valid(self,form):
        logged_in_user=self.request.user
        form.instance.author=logged_in_user

        return super().form_valid(form)                


class BlogDeleteView(DeleteView):
    template_name = "blogapp/blogdelete.html"
    model = Article
    success_url = "/bloglist/"


class BlogUpdateView(UpdateView):
    template_name = "blogapp/blogcreate.html"
    form_class = BlogForm
    model = Article
    success_url = "/bloglist/"

templates/blogapp/blogbase.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
 {% block css %}

 {% endblock %}	
</head>
<body class="container-fluid">
	<a href="{% url 'blogapp:bloghome' %}">Home</a> |
	<a href="{% url 'Touristapp:home' %}">Exit blog</a> |
	<a href="{% url 'blogapp:bloglist' %}">BlogList</a>


	<hr>
{% block content %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

{% block js %}


{% endblock %}
</body>
</html>

templates/blogapp/blogcreate.html
{% extends 'blogapp/blogbase.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6 mx-auto">
		
		<h3>Tour Form</h3>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-primary">Submit data</button>
		</form>
	</div>
</div>
{% endblock %} 

templates/blogapp/blogdelete.html
{% extends 'blogapp/blogbase.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6 mx-auto">
		
		<h3>Tour Form</h3>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<h3>Are you sure</h3>
			<button class="btn btn-danger">Yes</button>
			<a class="btn btn-info" href="{% url 'blogapp:bloglist' %}">No</a>
		</form>
	</div>
</div>
{% endblock %}

templates/blogapp/blogdetail.html
{% extends 'blogapp/blogbase.html' %}

{% block title %}Home{% endblock %}

{% block content %}
 <h3 class="text-success">Welcome to blogsite</h3>

<div class="row">
	<div class="col-md-7">
      	<h3 class="text-info">Title: {{blogde.title}}</h3>
		<!-- <p>Slug:{{blogde.slug}}</p> -->
		<img src="{{blogde.image.url}}" width="800">
		<p class="text-warning">Content:  {{blogde.content}} </p>
		<p class="text-danger">Date: {{blogde.date}}</p>
		<p class="text-primary">Author: {{blogde.author}}</p>
		<p>Views: {{blogde.views}}</p>
		<h4>All Comments</h4>
		{% for comment in blogde.comment_set.all %}
		 <li>{{comment.text}}</li>
		 <p style="color: #582703;">by {{comment.commenter.username}} {{comment.date|timesince}} ago</p>

		{% empty %}
		 <li>No comments yet</li>
		{% endfor %} 


	</div>	
	<div class="col-md-5">
		<h3 class="text-center text-info my-au">You may also be interested in</h3>
		{% for blog in articlelist %}
		{% if blog != blogde %}
			<div class="col mt-3" align="middle">
				<li><a href="{% url 'blogapp:blogdetail' blog.id %}">{{blog.title}}</a></li>
				<!-- <p align="right"/>Posted on: {{blog.date|timesince}} ago</p> -->
		
				<img src="{{blog.image.url}}" width="150" height="150"  class="img-fluid"> 
			</div>
		{% endif %}
		{% endfor %}
	</div>
</div>	
				
{% endblock %}

templates/blogapp/bloghome.html
{% extends 'blogapp/blogbase.html' %}

{% block title %}Home{% endblock %}

{% block content %}
 <h3>Welcome to blogsite</h3>
{% endblock %}

templates/blogapp/bloglist.html
{% extends 'blogapp/blogbase.html' %}

{% block title %}Home{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

{% endblock %} 

{% block content %}

<h3>BlogList</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Title</th>
      <th scope="col">Image</th>
      <th scope="col">Content</th>
      <th scope="col">Date</th>
      <th scope="col">Author</th>
      <th scope="col">Views</th>
      <th scope="col">Active</th>

    </tr>
  </thead>
<tbody>
{% for blog in allblog %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td class="text-danger">{{blog.title}}</td>
    
      <td><img src="{{blog.image.url }}" width="50"></td>
      <td class="text-info">{{blog.content|truncatewords:"5"}}</td>
      <td class="text-success">{{blog.date|timesince}} ago</td>
      <td class="text-warning">{{blog.author}}</td>
      <td class="text-dark">{{blog.views}}</td>

      <td>
        <a href="{% url 'blogapp:blogdetail' blog.id %}" class="btn btn-primary" mt-3>Detail</a>
        <a href="{% url 'blogapp:blogcreate' %}" class="btn btn-warning" mt-3>create</a> 
        <a href="{% url 'blogapp:blogupdate' blog.id %}" class="btn btn-info" mt-3>Update</a>
        <a href="{% url 'blogapp:blogdelete' blog.id %}" class="btn btn-danger" mt-3>Delete</a>
      </td>

    </tr>
    
{% endfor %}
    
</tbody>
</table>


{% endblock %}

{% block js %}
<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
  $(document).ready( function () {
    $('.table').DataTable();
} );
</script>
{% endblock %}