Touristapp/urls.py
from django.urls import path
from .views import * 

app_name='Touristapp'
urlpatterns=[
  path('',HomeView.as_view(),name="home"),
  path('about/',AboutView.as_view(),name="about"),
  path('tour/',TourPackageView.as_view(),name="tourpackage"),
  path('tour/<int:pk>/detail/',TourPackageDetailView.as_view(),name="tourpackagedetail"),
  path('tourpackage/',TourPackageCreateView.as_view(),name="tourpackagecreate"),
  path('tourpackage/<int:pk>/edit/',TourPackageUpdateView.as_view(),name="tourpackageupdate"),
  path('tour/<int:pk>/delete/',TourPackageDeleteView.as_view(),name="tourpackagedelete"),
  path('contact/',ContactUsView.as_view(),name="contactus"),
  path('login/',LoginView.as_view(),name="login"),
  path('logout/',LogoutView.as_view(),name="logout"),
  path('register/',RegistrationView.as_view(),name="registration"),
  path('bankapi/',BankApiView.as_view(),name="bankapi"),
  path('protected-page/',ProtectedView.as_view(),name="protected"),

] 

Touristproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Touristapp.urls')),
    path('blogsite/',include('blogapp.urls')),

]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from .views import * 


app_name='blogapp'
urlpatterns=[
 path('',BlogHomeView.as_view(),name="bloghome"),
 path('bloglist/',BlogListView.as_view(),name="bloglist"),
 path('blog/<int:pk>/detail/',BlogDetailView.as_view(),name="blogdetail"),
 path('blogcreate/',BlogCreateView.as_view(),name="blogcreate"),
 path('blog/<int:pk>/update/',BlogUpdateView.as_view(),name="blogupdate"),
 path('blog/<int:pk>/delete/',BlogDeleteView.as_view(),name="blogdelete"),

]

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


{% endblock %}

templates/bankapi.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<input type="text" placeholder="search" name="" id="search">
<div class="row container banks">
	{% for bank in banks %}
	<div class="col-md-3 bank">
		<div class="m-1 bg-info p-2 m-1">
		<img src="{% static 'img/bank.jpg' %}">
			
		<h4 class="text-white">{{bank.bank_name}}</h4>
		<p>IFSC:{{bank.ifsc}}</p>

		<p>Branch:{{bank.branch}}</p>
		<p>Address:{{bank.address}}</p>
		<p>city:{{bank.city}}</p>
		<p>State:{{bank.state}}</p>
		<p>District:{{bank.district}}</p>
		</div>
	</div>
	{% endfor %}
</div>>
{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href=" https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" >
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

  {% block css %}

  {% endblock %}
</head>
</head>
<body class="container">

<div class="row">
    <div class="col">
      	<h1 class="text-center text-info" >Online Tourist System</h1>
    </div>
</div>

<div class="topnav">
  <a class="active" href="{% url 'Touristapp:home' %}">Home</a>
  <a href="{% url 'Touristapp:about' %}">About</a>
  <a href="{% url 'Touristapp:tourpackage' %}">Tourist Package</a>
  <a href="{% url 'Touristapp:contactus' %}">Contactus</a>
  <a href="{% url 'blogapp:bloghome' %}">Blogapp</a>
  {% if request.user.is_authenticated %}
  <a href="" style="color: red;float: right;">{{request.user}}</a>
  <a style="float:right" class="active" href="{% url 'Touristapp:logout' %}">Logout</a>
  {% else %}
  <a style="float:right" class="active" href="{% url 'Touristapp:registration' %}">Sign up</a>
  <a style="float:right" class="active" href="{% url 'Touristapp:login' %}">Login</a>
 
  {% endif %}

</div>

<hr>
<!-- <div class="row"  style="background: width: 200%;
    height: 500px;
    background-image: url({% static 'img/cover.jpg' %});
    background-size: contain;
    background-repeat: no-repeat;
    ">
</div>	 -->

		
<hr>	
{% block content %}

{% endblock %}
<hr>
<footer class="page-footer font-small blue bg-success">
	<div class="footer-copyright text-center py-3">0 2019 copyright:
	</div>	
</footer>  



<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

{% block js %}


{% endblock %}
</body> 
</html>

templates/contactus.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
ssssss

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="row">
	<div class="col-md-12">
		<img class="image-responsive" src="{% static 'img/cover.jpg' %}" class="img-fluid" style="width: 100%; object-fit: cover; height: 500px;">
</div>		

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style type="text/css">
	#id_username{
		color: red;
	}
	#id_password{

	}
</style>
<div class="row">
	<div class="col-md-4 mx-auto">
		{% if error %}
		<li class="text-danger">{{error}}</li>
		{% endif %}
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
		    <button class="btn btn-default primary">Login</button>

		</form>	
	</div>

</div>
{% endblock %}

templates/protectedpage.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>This is too much secrete page.</h1>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="form-container">
	
 <div class="row">

	<div class="col-md-4 mx-auto">
		
		<h4>Registration Form</h4>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button>Sign up</button>
		</form>	
	</div>

 </div>
</div>

{% endblock %}

templates/tourpackage.html
{% extends 'base.html' %}


{% block css %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

{% endblock %} 


{% block content %}
<h3>
	All Articles
</h3>


  
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Name</th>
      <th scope="col">Image</th>
      <th scope="col">Location</th>
      <th scope="col">Amount</th>
      <th>Action</th>

    </tr>
  </thead>
<tbody>
{% for tour in allpackage %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{tour.title}}</td>
      <td><img src="{{tour.image.url }}" width="50"></td>
      <td>{{tour.location}}</td>
      <td>{{tour.amount}}</td>

      <td>
        <a href="{% url 'Touristapp:tourpackagedetail' tour.id %}" class="btn btn-primary">Detail</a>
        <a href="{% url 'Touristapp:tourpackageupdate' tour.id %}" class="btn btn-info">Update</a>
        <a href="{% url 'Touristapp:tourpackagedelete' tour.id %}" class="btn btn-danger">Delete</a>
      </td>

    </tr>
    
{% endfor %}
    
  </tbody>
</table>

{% endblock %}

{% block js %}
<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
  $(document).ready( function () {
    $('.table').DataTable();
} );
</script>
{% endblock %}

templates/tourpackagecreate.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="row">
	<div class="col-md-6 mx-auto">
		
		<h3>Tour Form</h3>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-primary">Submit data</button>
		</form>
	</div>
</div>
{% endblock %}

templates/tourpackagedelete.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<form method="POST">
	{% csrf_token%}
	<h3>Are you sure</h3>
	<button class="btn btn-danger">Yes</button>
	<a class="btn btn-info" href="{% url 'Touristapp:tourpackage' %}">No</a>
</form>
{% endblock %}

templates/tourpackagedetail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}


<h3>Title:{{package.name}}(viewed {{package.views}} times)</h3>
<img src="{{package.image.url}}" width="800">
<p>Location:{{package.content}}</p>
<p>Amount:{{package.author}}</p>


{% endblock %}